package com.readALoud.entities;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


@Entity
@Table(name="COMMENTS")
public class Comments implements Serializable
{
	private static final long serialVersionUID = 1L;
	
	Comments(){

	}
	public Comments(String comments,User user,Book book,Date currentDate){ //parameterized constructor
		this.setCommentsDesc(comments);
		currentDate=new Date();
		this.setCreationDate(currentDate);
		this.setUser(user);
		this.setBook(book);
	}
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="CID",updatable=false,nullable=false)
	private Long id;//primary key generated by hibernate
	
	@ManyToOne
	@JoinColumn(name="book_id",nullable=false)
	private Book book;
	
	@Column(name="comments",nullable=false)
	private String commentsDesc;
		
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="creation_date",nullable=false)
	private Date creationDate;
		
	@ManyToOne
	@JoinColumn(name="uid",nullable=false) 
	private User user; //one comment by one user
		
	public void setCommentsDesc(String comments) {
		this.commentsDesc = comments;
	}
	public String getCommentsDesc() {
		return commentsDesc;
	}
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}	
	public Date getCreationDate() {
		Date returnDate=this.creationDate;
		return returnDate;
	}	
	@Override
	public String toString(){	
		StringBuilder sb = new StringBuilder();
		sb.append("(id=");
		sb.append(id);
		sb.append(",comments= ");
		sb.append(commentsDesc);
		sb.append(",creation date= ");
		sb.append(creationDate);
		sb.append(",Commentors=");
		sb.append(this.getUser()+")");
		return super.toString();		
	}
	@Override
	public boolean equals(Object obj) {
			
		return super.equals(obj);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}

	@SuppressWarnings("unused")
	private void setId(Long id) {
		this.id = id;
	}
	public Long getId() {
		Long returnId;
		returnId=this.id;
		return returnId;
	}
	public void setUser(User user) {
		this.user=user;	
	}
	public User getUser() {
		return user;
	}
	public void setBook(Book bookComments) {
		this.book = bookComments;
	}
	public Book getBook() {
		return book;
	}
	
}
